import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { Platform } from '@ionic/angular';
import { Router } from '@angular/router';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { DataService } from '../../services/data/data.service';
import { ViewEncapsulation } from '@angular/core';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-paper-work',
  templateUrl: './paper-work.page.html',
  styleUrls: ['./paper-work.page.scss'],
  encapsulation: ViewEncapsulation.None
})
export class PaperWorkPage implements OnInit {
  myForm: FormGroup;
  submitAttempt = false;
  data: any;
  columns: any;
  rows: any[] = [];
  editing = false;

  constructor(
    public platform: Platform,
    private router: Router,
    public formBuilder: FormBuilder,
    private dataService: DataService
  ) {
    this.myForm = this.formBuilder.group({
      email: ['', Validators.required],
      password: ['', Validators.required]
    });
  }
  
  ngOnInit() {
    this.columns = [
      { name: 'A' },
      { name: 'B' },
      { name: 'D' },
      { name: 'E' },
      { name: 'F' },
      { name: 'G' },
      { name: 'H' },
      { name: 'I' },
      { name: 'J' },
      { name: 'K' },
      { name: 'L' },
      { name: 'M' },
      { name: 'N' },
      { name: 'O' },
      { name: 'P' },
      { name: 'Q' },
      { name: 'R' },
      { name: 'S' },
      { name: 'T' },
      { name: 'U' },
      { name: 'V' },
      { name: 'W' },
      { name: 'X' },
      { name: 'Y' },
      { name: 'Z' },
    ];

    this.columns = [
      { name: 'Name' },
      { name: 'Company' },
      { name: 'Genre' }
    ];

    const a = {
      "movies": [
          {
              "name": "Escape Room Escape Room Escape Room",
              "company": "Columbia Pictures",
              "genre": "Horror"
          },
          {
              "name": "Rust Creek",
              "company": "IFC Films",
              "genre": "Drama"
          },
          {
              "name": "American Hangman",
              "company": "Hangman Productions",
              "genre": "Thriller"
          },
          {
              "name": "The Upside",
              "company": "STX Entertainment",
              "genre": "Comedy"
          },
          {
              "name": "Replicas",
              "company": "Entertainment Studios",
              "genre": "Sci-Fi"
          },
          {
              "name": "After Darkness",
              "company": "Grindstone Group",
              "genre": "Drama"
          },
          {
              "name": "Glass",
              "company": "Universal Pictures",
              "genre": "Superhero"
          },
          {
              "name": "Close",
              "company": "Netflix",
              "genre": "Action"
          },
          {
              "name": "The Final Wish",
              "company": "BondIt Capital",
              "genre": "Horror"
          },
          {
              "name": "Serenity",
              "company": "Aviron Pictures",
              "genre": "Drama"
          },
          {
              "name": "Miss Bala",
              "company": "Columbia Pictures",
              "genre": "Thriller"
          },
          {
              "name": "Velvet Buzzsaw",
              "company": "Netflix",
              "genre": "Comedy"
          }
      ]
    }

    const b = {
      "data": [
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          {
            "a": "",
            "b": "",
            "c": "",
            "d": "",
            "e": "",
            "f": "",
            "g": "",
            "h": "",
            "i": "",
            "j": "",
            "k": "",
            "l": "",
            "m": "",
            "n": "",
            "o": "",
            "p": "",
            "q": "",
            "r": "",
            "s": "",
            "t": "",
            "u": "",
            "v": "",
            "w": "",
            "x": "",
            "y": "",
            "z": "",
          },
          
      ]
    }

    this.rows = a.movies;
    // this.rows = b.data;
  }

  log(cell, rowIndex) {
    cell = cell.toLowerCase();
    console.log(cell)
    console.log(this.rows[rowIndex][cell])
    console.log(this.rows)
  }

  updateValue(event, cell, rowIndex) {
    // this.editing[rowIndex + '-' + cell] = false;
    cell = cell.toLowerCase();
    this.rows[rowIndex][cell] = event.target.value;
    this.rows = [...this.rows];
    console.log('UPDATED!', this.rows[rowIndex][cell]);
  }

  toggleEditing() {
    if (this.editing) {
      this.editing = false;
    } else {
      this.editing = true;
    }
    console.log(this.rows)
  }

  ionViewWillEnter() {
  }
  
  ionViewWillLeave() {
  }
}